include: package:flutter_lints/flutter.yaml

linter:
  rules:
     avoid_print: true
     prefer_single_quotes: true

bloc:
 rules:
   avoid_build_context_extensions: false
   avoid_flutter_imports: error
   avoid_public_bloc_methods: error
   avoid_public_fields: warning
   prefer_build_context_extensions: false
   prefer_file_naming_conventions: true
   prefer_void_public_cubit_methods: info