// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.constants.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4XtisAf1gSBO3rOwHiA93_WzcY2C_xU',
    appId: '1:524769488861:android:9cf6bff4a4c3700be7d034',
    messagingSenderId: '524769488861',
    projectId: 'project-tweety',
    storageBucket: 'project-tweety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1xCxJOLChyPBmTjbsh9c4n6d6cU9K2M',
    appId: '1:524769488861:ios:f6c14fff94ffc68ee7d034',
    messagingSenderId: '524769488861',
    projectId: 'project-tweety',
    storageBucket: 'project-tweety.firebasestorage.app',
    androidClientId: '524769488861-32ok4s0navpbgdhrtlbug4krrt541lqr.apps.googleusercontent.com',
    iosClientId: '524769488861-fv4e73m5f9r0n7046vejo0aeropm5ek7.apps.googleusercontent.com',
    iosBundleId: 'dev.euanscott.projecttweety',
  );
}
